---
title: "GLORIA 氣候資料處理"
output: WORD
---

# 概要
統整資料處理與分析過程。主要有以下幾項。
1. datalogger資料清理。
2. ERA5資料統整。
3. ERA5資料與datalogger資料結合
4. 結果分析與繪圖

## 主要package
```{r}
library(imputeTS) #time serise analysis
library(data.table)
library(broom) #get the lm coefficient
library(ggplot2) #plot
library(mondate) # deal with the date data

```


## 處理datalogger資料
概要：讀取datalogger資料，並將其日期轉換成GMT+8,再建立每筆紀錄的年-月-日欄位

```{r}
Sys.setlocale("LC_TIME", "English") #Set up the time format to English.
w_data <- fread('C:/Users/joker/Google 雲端硬碟/GLORIA_個人處理/Weather_data/temp_20200809_corrected.csv') #The temperature data from datalogger
w_data[,yyddhh:=as.POSIXct(timestamp,format="%Y-%m-%d %H:%M:%S",tz ="" )+8*60*60]
# the time zone of column "timestamp" is GMT +0. therefore, it has to be converted to GMT +8 
w_data[,year:=year(yyddhh)][,month:=month(yyddhh)][,day:=day(yyddhh)][,hour:=hour(yyddhh)]
write.csv(w_data,'C:/Users/joker/Google 雲端硬碟/GLORIA_個人處理/Weather_data/temp_20200809_corrected_add_date.csv')
```

## 處理 ERA5 資料
概要：將ERA5的資料統整合併，日期轉換，並將數值轉換成一般常用單位(溫度為攝氏，雨量為mm)。
```{r}
#the region and period most be text. The "region" is the region code, like "SYU" or "DAS". The "path" is the folder path of data.
ERA_data <- function(region,path){
  Sys.setlocale("LC_TIME", "English") #Set up the time format to English.
  folder <- paste0(path,region,"/")
  namelist <- list.files(folder)
  data_list <- lapply(namelist,function(x){
  fread(paste0("rawdata/ERA_5/daily_data/",region,"/",x))})
  dataset <- rbindlist(data_list)
  colnames(dataset) <- c('date','temp','rain')
  dataset[,date:=as.Date(date,format='%b %d, %Y')][
  ,temp:=temp-273.15][
  ,rain:=rain*1000]
  return(dataset)
  }
path <- "rawdata/ERA_5/daily_data/"
result <- NULL
for (i in c("SYU","DAS")){
  tb <- data.table(region=i, ERA_data(i,path))
  result <- rbind(result,tb)
  }

write.csv(result,'processing/ERA5_daily.csv')
```
## datalogger 資料整理並計算
概要：將datalogger資料統整計算各個山頭、各方位的日均溫，刪除資料筆數未滿24小時者
```{r}

GLA_temp_d <- function(reg,rdata){ # 'reg' is the region code, 'rdata' is the datalogger data.
t_h <- rdata[region==reg]
daily <- t_h[,.(temp=mean(temperature),n=.N),
                 by=.(region,summit,direction,year,month,day,datalogger)]
daily[,date:=as.Date(paste(year,month,day,sep='-'))] #calculate the daily temp of each dir and each datalogger
daily <- daily[n>23]#刪除未滿24小時的資料
d_com <- daily[,.(temp=mean(temp),n=.N),
                       by=.(region,summit,direction,date)] #calculate the daily temp of each dir (combining the datalogger data)
return(d_com)
}

reg <- c('DAS','SYU')
era5_d <- fread('processing/ERA5_daily.csv')
base_wdata <- rbindlist(lapply(reg, function(x){GLA_temp_d(x,w_data)}))

setkey(Das_d,date)
setkey(era5_d,date)
wdata_c <- base_wdata[era5_d,on=.(date=date,region=region)]
write.csv(Das_era,paste0('E:/忍者/GLORIA_個人處理/Weather_data/',reg,'/cobim_w_era_data.csv'))
#######################################################
```

```{r}
wdata <- w_data
lm_era_real <- function(reg,wdata,era5_d,S){ 
  m_fr <- NULL
  w_result <- NULL
  for (i in S){
    i="YAT"
    rd <- wdata[summit==`i`]
    dir <- unique(rd[,direction])
    for (j in 1:length(unique(dir))){
        r2 <- rd[direction==dir[j],]
        m_t <- lm(temp~i.temp,data=r2)
        ######save the model coefficient
        m_r <-cbind(data.table(model="Temp",summit=S[i],direction=dir[j]),glance(m_t)[1:6]) #glance from the package "broom"
        m_fr <- rbind(m_fr,m_r)
        ################ merge the rdata and predict
        pre <- merge(r2[,1:7],era5_d,on=.(date=date),all=T)
    setnames(pre,'temp.y','i.temp')
    pre[,temp.p:=predict(m_t,pre)]
    pre[,summit:=S[i]][,direction:=dir[j]][,region:=reg]
    pre[is.na(temp.x),c('temp.x','type'):=.(temp.p,"p") ]
    pre[,10:14:=NULL]
    pre[,8:=NULL]
    w_result <- rbind(w_result,pre)
    }#finished j looping
} #i looping
return(list(m_fr,w_result))
}
S <- c('SEN','SUN','YAT','JNJ','DSH','TSW')
result <- lm_era_real(reg,Das_era,era5_d,S)
```

